ACCESS_TOKEN = 'sl.BWsR7uw_bg-2q8TIqVCHLfUTPVrd3kfpGdpKe4lB1rzf6XfNXZmKb42rE68XxoMzxHA_PPLEr65xk_tb5QYBlWdpP4BgCctd7cqE7fNoAKZLYm8HJTkkicjyy-fidshUFTxAKHE'
FILE_TO_UPLOAD = 'photo_1.jpg'
RELATIVE_PATH_TO_FILE = f'resources/{FILE_TO_UPLOAD}'
